# Generated by Django 5.1.3 on 2024-11-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, null=True, related_name='Labels', to='labels.label', verbose_name='Labels'),
        ),
    ]
